name: ci
on:
  schedule:
    - cron: "10 10 */2 * *"
jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: generate
        run: make gen

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Adding new schemas
          commit_user_name: Yann Hamon
          commit_user_email: yann+github@mandragor.org
          commit_author: Yann Hamon <yann+github@mandragor.org>
