name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        prefix: ["v1.13"]
    env:
      K8S_VERSION_PREFIX: ${{ matrix.prefix }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: generate
        run: make gen

      - uses: stefanzweifel/git-auto-commit-action@v4